apiVersion: v1
kind: Service
metadata:
  name: nodeport
  namespace: default
spec:
  selector:
    app: nginx-tool
  ports:
    - name: web
      port: 80
      protocol: TCP
      nodePort: 30080
  type: NodePort
