apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: contractors
subjects:
  - kind: User
    name: johndoe
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: contractor
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: contractor
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "watch", "list"]
